mode: rule

proxies:
  - name: "BNET"
    type: socks5
    server: 203.76.220.168
    port: 1052
    username: exrex
    password: exrex

  - name: "Windstream Communication"
    type: socks5
    server: 103.143.139.173
    port: 1080
    username: 1
    password: 1

  - name: "Asian Network"
    type: socks5
    server: 103.106.241.235
    port: 6969
    username: "@bdiix_bypass"
    password: "@bdiix_bypass"

  - name: "STLBD"
    type: socks5
    server: 103.166.253.92
    port: 1088
    username: test
    password: test

  - name: "Carnival"
    type: socks5
    server: 103.91.231.244
    port: 1088
    username: test
    password: test

proxy-groups:
  - name: "DOWNLOAD"
    type: load-balance
    strategy: round-robin
    url: https://www.gstatic.com/generate_204
    interval: 10
    proxies:
      - BNET
      - Windstream Communication
      - Asian Network
      - STLBD
      - Carnival


rules:
  - MATCH,DOWNLOAD